### ISSUE TITLE
How to obtain mit_b2.pth?

### ISSUE THREAD

**Issue by AnupKumarGupta** [Qiming-Huang/ssformer#1]
When I try to run the test script, I get the following error. 

No such file or directory: '/mnt/DATA-1/DATA-2/Feilong/scformer/models/mit/mit_b2.pth'

How can I obtain the aforementioned .pth file?

**Comment by Qiming-Huang** [comment]
> When I try to run the test script, I get the following error.
> 
> No such file or directory: '/mnt/DATA-1/DATA-2/Feilong/scformer/models/mit/mit_b2.pth'
> 
> How can I obtain the aforementioned .pth file?

thanks for submitting this issue. You can download mit_b2.pth from this [link](https://drive.google.com/file/d/1_DzrlOYMwMKwi7NvI2QC51tAL0xf4XUQ/view?usp=sharing)

**Comment by lzz2131** [comment]
when I try to run the train.py, I get the following error about all layernorm.
AttributeError: 'LayerNorm' object has no attribute 'affine'
How can I slove it?

**Comment by Qiming-Huang** [comment]
> when I try to run the train.py, I get the following error about all layernorm. AttributeError: 'LayerNorm' object has no attribute 'affine' How can I slove it?

- you may try this: `pip install thop-0.0.31.post2005241907-py3-none-any.whl` .  [ref](https://zhuanlan.zhihu.com/p/500977499)

**Comment by id4su** [comment]
When I run  the test.py,I get following error,can you give me this model's link?
No such file or directory: '/mnt/DATA-1/DATA-2/Feilong/scformer/models/mit/mit_b4.pth

**Comment by Qiming-Huang** [comment]
> > when I try to run the train.py, I get the following error about all layernorm. AttributeError: 'LayerNorm' object has no attribute 'affine' How can I slove it?
> 
> * you may try this: `pip install thop-0.0.31.post2005241907-py3-none-any.whl` .  [ref](https://zhuanlan.zhihu.com/p/500977499)

check the uploaded requirements.txt and try to install the packages on the same version.
