### ISSUE TITLE
Can't find mit_b4.pth file.

### ISSUE THREAD

**Issue by nikhilroxtomar** [Qiming-Huang/ssformer#10]
Hi,

I am working on your method (SSFormer). I am unable to find the pre-trained checkpoint file: mit_b4.pth
It would be really great if you can help me with this.  You can also email me at nikhilroxtomar@gmail.com

Best Regards,
Nikhil

**Comment by Qiming-Huang** [comment]
> 

Hi, mit_b4.pth can be downloaded by this [link](https://drive.google.com/file/d/1X1LUicKZBRp7Fk8Kr7Iwz8tyjI-RAgF_/view?usp=sharing)
