### ISSUE TITLE
Attention HeatMap

### ISSUE THREAD

**Issue by dumyCq** [Qiming-Huang/ssformer#5]
I want to plot the attention heatmap that is similar to your Fig 2.
I wonder how you did these.

**Comment by dumyCq** [comment]
Does this attention map use the average of feature maps to generate

**Comment by Qiming-Huang** [comment]
> Does this attention map use the average of feature maps to generate

We used CAM for visualization. You may want to check this repo: https://github.com/frgfm/torch-cam

**Comment by sjc-lbj** [comment]
I want to know how the author reproduced the accuracy of each evaluation index about -S and -L in the file. When I ran test.py, only the accuracy of dice coefficient would appear. May I ask how the author reproduced other indicators
![1673871172171](https://user-images.githubusercontent.com/115783600/212675646-ea412354-4dcf-4742-ac23-60c95157af78.png)
