### ISSUE TITLE
May I ask why the experimental results in the paper are so different from the experimental results in the github code base？

### ISSUE THREAD

**Issue by MOONWZ** [Qiming-Huang/ssformer#7]
![image](https://user-images.githubusercontent.com/74870759/204753319-5d7e326f-b44d-419f-a4f9-d20c2c5233e7.png)
![image](https://user-images.githubusercontent.com/74870759/204753353-0cea47c0-727b-4007-8680-1df10a9cf653.png)
May I ask why the experimental results in the paper are so different from the experimental results in the github code base？

**Comment by Qiming-Huang** [comment]
> 

The result on Github is an old version (To avoid subsequent misleading, I removed the results displayed on GitHub), please refer to the final result depicted in the paper. Thanks.

**Comment by sjc-lbj** [comment]
> ![image](https://user-images.githubusercontent.com/74870759/204753319-5d7e326f-b44d-419f-a4f9-d20c2c5233e7.png) ![image](https://user-images.githubusercontent.com/74870759/204753353-0cea47c0-727b-4007-8680-1df10a9cf653.png) May I ask why the experimental results in the paper are so different from the experimental results in the github code base？

Can you fully reproduce the evaluation indicators in the paper？

**Comment by WangZhi-wz** [comment]
> > ![image](https://user-images.githubusercontent.com/74870759/204753319-5d7e326f-b44d-419f-a4f9-d20c2c5233e7.png) ![image](https://user-images.githubusercontent.com/74870759/204753353-0cea47c0-727b-4007-8680-1df10a9cf653.png) May I ask why the experimental results in the paper are so different from the experimental results in the github code base？
> 
> Can you fully reproduce the evaluation indicators in the paper？

Yes, training on these two datasets individually basically achieves the results of the paper

**Comment by sjc-lbj** [comment]
> > > ![image](https://user-images.githubusercontent.com/74870759/204753319-5d7e326f-b44d-419f-a4f9-d20c2c5233e7.png) ![image](https://user-images.githubusercontent.com/74870759/204753353-0cea47c0-727b-4007-8680-1df10a9cf653.png) May I ask why the experimental results in the paper are so different from the experimental results in the github code base？
> > 
> > 
> > Can you fully reproduce the evaluation indicators in the paper？
> 
> Yes, training on these two datasets individually basically achieves the results of the paper

When I run testpy, only dice accuracy appears. May I ask how other indicators are repeated, such as iou?

**Comment by sjc-lbj** [comment]
> > > ![image](https://user-images.githubusercontent.com/74870759/204753319-5d7e326f-b44d-419f-a4f9-d20c2c5233e7.png) ![image](https://user-images.githubusercontent.com/74870759/204753353-0cea47c0-727b-4007-8680-1df10a9cf653.png) May I ask why the experimental results in the paper are so different from the experimental results in the github code base？
> > 
> > 
> > Can you fully reproduce the evaluation indicators in the paper？
> 
> Yes, training on these two datasets individually basically achieves the results of the paper
Hello, may I ask how do you deal with the problem of multiple masks in the data science bowl 2018 set to recover the accuracy of the original paper

**Comment by sjc-lbj** [comment]
> > > ![image](https://user-images.githubusercontent.com/74870759/204753319-5d7e326f-b44d-419f-a4f9-d20c2c5233e7.png) ![image](https://user-images.githubusercontent.com/74870759/204753353-0cea47c0-727b-4007-8680-1df10a9cf653.png) May I ask why the experimental results in the paper are so different from the experimental results in the github code base？
> > 
> > 
> > Can you fully reproduce the evaluation indicators in the paper？
> 
> Yes, training on these two datasets individually basically achieves the results of the paper
Hello, may I ask how do you deal with the problem of multiple masks in the data science bowl 2018 set to recover the accuracy of the original paper
